FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=target/ms-aplazo-payment-quote-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} appAplazo.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/appAplazo.jar"]